server:
  port: 8081

spring:
  application:
    name: cash
  datasource:
    url: jdbc:postgresql://localhost:5432/cash
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true