server:
  port: 8081

spring:
  application:
    name: cash
  datasource:
    url: jdbc:postgresql://localhost:5432/cash
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
#  flyway:
#    url: jdbc:postgresql://localhost:5432/cash
#    username: user
#    password: password